name: Deploy stage
on:
  push:
    branches:
      - "homologacao"
jobs:
  build:
    name: Deploy Stage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/home/semaloapi/Apps/app-painel-entregas-externo/stage"

      - name: Install Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/semaloapi/Apps/app-painel-entregas-externo/stage
            yarn

      - name: Build Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/semaloapi/Apps/app-painel-entregas-externo/stage
            yarn build
